# Generated by Django 4.0.2 on 2022-02-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registeredagain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_Nuumber', models.CharField(max_length=100000)),
                ('passout', models.CharField(max_length=122, null=True)),
                ('branch', models.CharField(max_length=122, null=True)),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('address_work', models.TextField(null=True)),
                ('permanent_address', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Registered',
        ),
    ]
