# Generated by Django 4.0.2 on 2022-02-07 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_registeredagain_delete_registered'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registeredagain',
            new_name='Registered',
        ),
    ]
