# Generated by Django 4.0.2 on 2022-02-07 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_registeredagain_registered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registered',
            old_name='address_work',
            new_name='Address_Work',
        ),
        migrations.RenameField(
            model_name='registered',
            old_name='branch',
            new_name='Branch',
        ),
        migrations.RenameField(
            model_name='registered',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='registered',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='registered',
            old_name='passout',
            new_name='Passout',
        ),
        migrations.RenameField(
            model_name='registered',
            old_name='permanent_address',
            new_name='Permanent_Address',
        ),
        migrations.RenameField(
            model_name='registered',
            old_name='serial_Nuumber',
            new_name='Serial_Number',
        ),
    ]
