# Generated by Django 4.0.2 on 2022-02-07 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_address_work_registered_address_work_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registered',
            old_name='Name',
            new_name='name',
        ),
    ]
