# Generated by Django 4.0.2 on 2022-02-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_address_work_registered_address_work_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registered',
            name='serial_Number',
        ),
    ]
